name: Node.js CI

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Optional: Fetch recent history if needed (for caching purposes)

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: ./front
      run: npm install

      # Step 5: Build the frontend
    - name: Build frontend
      working-directory: ./front
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: ./front/dist
